services: docker

env:
  global:
    - VM_DIR: /vagrant
  matrix:
    - VCCW_ENV='{ "hostname": "127.0.0.1" }'
    - VCCW_ENV='{ "hostname": "127.0.0.1", "lang": "ja", "plugins": [ "simple-map" ], "theme": "twentyfifteen" }'

before_install:
  - bundle install --path vendor/bundle
  - /usr/bin/env bash bin/run-docker.sh

script:
  - bundle exec rake spec
