- hosts: all
  tasks:
    # Create SSL Keys
    - name: create ssl Keys
      become: yes
      command: openssl req -batch -new -x509 -newkey rsa:2048 -nodes -sha256 \
        -subj /CN=*.{{ vccw.hostname }}/O=oreore -days 3650 \
        -keyout /etc/apache2/ssl/{{ vccw.hostname }}.key \
        -out /etc/apache2/ssl/{{ vccw.hostname }}.crt

    # Setup Document Root
    - name: Place /etc/apache2/sites-available/site.conf
      become: yes
      template:
        src: templates/site.conf
        dest: "/etc/apache2/sites-available/{{ vccw.hostname }}.conf"
      notify:
        - restart apache2

    # enable wordpress.conf
    - name: enable wordpress.conf
      become: yes
      command: a2ensite {{ vccw.hostname }}
      notify:
        - restart apache2

    # disable default
    - name: disable 000-default.conf
      become: yes
      command: a2dissite 000-default
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      become: yes
      service: name=apache2 state=restarted
