- hosts: all
  vars:
    wp_cli_bin_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

  tasks:

    # Setup bash
    - name: Place ~/.bash_profile
      become: no
      template:
        src: templates/.bash_profile
        dest: "{{ ansible_env.HOME }}/.bash_profile"
    - name: Place ~/.bash.d/
      become: no
      file:
        path: "{{ ansible_env.HOME }}/.bash.d"
        state: directory
    - name: Place ~/.bash.d/vccw.sh
      become: no
      template:
        src: templates/vccw.sh
        dest: "{{ ansible_env.HOME }}/.bash.d/vccw.sh"

    # Install Composer libraries
    - name: Create ~/.composer/
      file:
        path: "{{ ansible_env.HOME }}/.composer/"
        state: directory
    - name: Setup composer.json
      template:
        src: templates/composer.json
        dest: "{{ ansible_env.HOME }}/.composer/composer.json"
        force: no
    - name: Install Composer libraries
      composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "{{ ansible_env.HOME }}/.composer"
      with_items: "{{ vccw.composers | default([]) }}"
      ignore_errors: yes

    # Install WP-CLI
    - name: Install WP-CLI
      become: yes
      get_url:
        url: "{{ wp_cli_bin_url }}"
        dest: /usr/local/bin/wp
        mode: 0755
        force: yes
    - name: Create ~/.wp-cli/
      file:
        path: "{{ ansible_env.HOME }}/.wp-cli/"
        state: directory
    - name: Create `~/.wp-cli/config.yml` on the Guest
      template:
        src: templates/guest-wp-cli-config.yml
        dest: "{{ ansible_env.HOME }}/.wp-cli/config.yml"
    - name: Create `/vagrant/wp-cli.yml`
      template:
        src: templates/host-wp-cli-config.yml
        dest: "{{ vccw.vagrant_dir }}/wp-cli.yml"
    - name: Install WP-CLI packages
      become: no
      shell: /bin/bash -lc "wp package install '{{ item }}'"
      with_items: "{{ vccw.wp_cli_packages | default([]) }}"
      ignore_errors: yes

    # Install Ruby gems
    - name: Place ~/.gemrc
      become: no
      template:
        src: templates/.gemrc
        dest: "{{ ansible_env.HOME }}/.gemrc"
    - name: Install Ruby gems
      become: no
      gem:
        name: "{{ item }}"
        state: latest
        user_install: yes
      with_items: "{{ vccw.ruby_gems | default([]) }}"
      ignore_errors: yes

    # Install npm packages
    - name: Place ~/.npmrc
      become: no
      template:
        src: templates/.npmrc
        dest: "{{ ansible_env.HOME }}/.npmrc"
    - name: Install npm packages
      become: no
      npm:
        name: "{{ item }}"
        global: yes
        executable: /usr/bin/npm
      with_items: "{{ vccw.npms | default([]) }}"
      ignore_errors: yes

    # Setup WordPress coding standards
    - name: Check `phpcs` exists.
      shell: bash -lc 'phpcs --help &> /dev/null; echo $?'
      register: is_phpcs
    - name: Setup WordPress coding standard
      shell: /bin/bash -lc "phpcs --config-set installed_paths {{ ansible_env.HOME }}/.composer/vendor/wp-coding-standards/wpcs"
      when: is_phpcs.stdout == "0"

    # WordPress i18n tools
    - name: Checkout WordPress i18n Tools
      subversion:
        repo: http://i18n.svn.wordpress.org/tools/trunk/
        dest: "{{ ansible_env.HOME }}/.wp-i18n/"
      ignore_errors: yes
