- hosts: all
  vars:
    wp_cli_bin_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    rubygems:
      - bundler
      - wordmove
      - mailcatcher
    npms:
      - grunt
      - grunt-init
      - grunt-cli
      - gulp
    composers:
      - hirak/prestissimo:*
      - phpmd/phpmd:*
      - phpunit/phpunit:*
      - squizlabs/php_codesniffer:*
      - wp-coding-standards/wpcs:*
      - sebastian/phpcpd:*
      - phploc/phploc:*
      - phing/phing:*

  tasks:

    # Setup bash
    - name: Place ~/.bash_profile
      template:
        src: templates/.bash_profile
        dest: "{{ ansible_env.HOME }}/.bash_profile"

    # Setup Document Root
    - name: Place /etc/apache2/sites-available/wordpress.conf
      become: yes
      template:
        src: templates/wordpress.conf
        dest: "/etc/apache2/sites-available/{{ vccw.hostname }}.conf"
      notify:
        - restart apache2

    # enable wordpress.conf
    - name: enable wordpress.conf
      become: yes
      command: a2ensite {{ vccw.hostname }}
      notify:
        - restart apache2

    # disable default
    - name: disable 000-default.conf
      become: yes
      command: a2dissite 000-default
      notify:
        - restart apache2


    # Install WP-CLI
    - name: Install WP-CLI
      become: yes
      get_url:
        url: "{{ wp_cli_bin_url }}"
        dest: /usr/local/bin/wp
        mode: 0755

    # Install Ruby gems
    - name: Install Ruby gems
      become: yes
      gem:
        name: "{{ item }}"
        state: latest
        user_install: no
        executable: /usr/bin/gem
      with_items: "{{ rubygems }}"

    # Install npm packages
    - name: Install npm packages
      become: yes
      shell: npm install -g {{ item }}
      with_items: "{{ npms }}"

    # Install PHP composer libraries
    - name: Install PHP composer libraries
      shell: /bin/bash -lc "composer global require '{{ item }}'"
      with_items: "{{ composers }}"

    # Setup WordPress coding standard
    - name: Setup WordPress coding standard
      shell: /bin/bash -lc "phpcs --config-set installed_paths {{ ansible_env.HOME }}/.composer/vendor/wp-coding-standards/wpcs"

    # WordPress i18n tools
    - name: Checkout WordPress i18n Tools
      subversion:
        repo: http://i18n.svn.wordpress.org/tools/trunk/
        dest: "{{ ansible_env.HOME }}/.wp-i18n/"

    # Just example
    - name: "hello {{ vccw.wp_box }}"
      shell: echo "{{ vccw.wp_box }}"

  handlers:
    - name: restart apache2
      become: yes
      service: name=apache2 state=restarted
