- hosts: all
  vars:
    path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}"
    dbname: "wordpress"
    dbuser: "wordpress"
    dbpassword: "wordpress"

  tasks:

  # Database Settings
  - name: create Database
    mysql_db:
      login_user: root
      login_password: wordpress
      name: "{{ dbname }}"
      state: present
  - name: create MySQL user
    mysql_user:
      login_user: root
      login_password: wordpress
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: "wordpress.*:ALL"
      host: "{{ vccw.db_host }}"
      state: present

  # download wordpress
  - name: wordpress core download
    command: |
      wp core download
      --path={{ path }}
      --locale={{ vccw.lang }}
      --version={{ vccw.version }}
      --force

  # wp-config.php
  - name: Delete wp-config.php
    file:
      state: absent
      path: "{{ path }}/wp-config.php"
  - name: create extra-php
    template:
      src: templates/extra-php.txt
      dest: "{{ path }}/extra-php.txt"
  - name: create wp-config.php
    shell: |
       wp core config \
       --path={{ path }} \
       --dbhost={{ vccw.db_host }} \
       --dbname={{ dbname }} \
       --dbuser={{ dbuser }} \
       --dbpass={{ dbpassword }} \
       --dbprefix={{ vccw.db_prefix }} \
       --locale={{ vccw.lang }} \
       --extra-php < {{ path | realpath }}/extra-php.txt
  - name: Delete extra-php
    file:
      state: absent
      path: "{{ path }}/extra-php.txt"

  # Reset Database
  - name: reset db reset
    command: wp db reset --yes --path={{ path }}
    when: vccw.reset_db_on_provision

  # install wordpress
  - name: install wordpress core
    command: |
      wp core install
      --path={{ path }}
      --url=http://{{ vccw.hostname }}/{{ vccw.wp_siteurl }}
      --title='{{ vccw.title }}'
      --admin_user={{ vccw.admin_user }}
      --admin_password={{ vccw.admin_pass }}
      --admin_email={{ vccw.admin_email }}

  - name: create index.php for wp_siteurl changed
    when: vccw.wp_siteurl != ''
    template:
      src: templates/index.php
      dest: "{{ vccw.document_root }}/index.php"
