- hosts: all
  tasks:
  - name: wordpress core download
    command: |
      wp core download
      --path={{ vccw.document_root }}/{{ vccw.wp_siteurl }}
      --locale={{ vccw.lang }}
      --version={{ vccw.version }}
      --force
