- hosts: all
  vars:
    path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}"
  tasks:
  - name: wordpress core download
    command: |
      wp core download
      --path={{ path }}
      --locale={{ vccw.lang }}
      --version={{ vccw.version }}
      --force
