- hosts: all
  tasks:
  # create default wp-cli config.
  - name: create ~/.wp-cli/
    file:
      path: "{{ ansible_env.HOME }}/.wp-cli/"
      state: directory

  - name: create ~/.wp-cli/config.yml
    template:
      src: templates/config.yml
      dest: "{{ ansible_env.HOME }}/.wp-cli/config.yml"
