# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

wp_box: miya0001/vccw
chef_cookbook_path: ./chef

network:
  hostname: wordpress.local
  ip: 192.168.33.10

wp:
  version: latest
  lang: en_US
  title: Welcome to the Vagrant
  multisite: false
  rewrite_structure: /archives/%post_id%
  path:
    wp_home: ''
    wp_siteurl: ''
  admin:
    user: admin
    pass: admin
  db:
    prefix: wp_
    host: localhost
  plugins:
    - theme-check
    - plugin-check
    - dynamic-hostname
  theme: ''
  options:
    blogdescription: Hello VCCW.
  config:
    force_ssl_admin: false
    wp_debug: true
    savequeries: false
  theme_unit_test: false
  theme_unit_test_uri: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
  # theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml
  reset_db_on_provision: true